# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{formtastic_extensions}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alexander Semyonov"]
  s.date = %q{2009-10-17}
  s.description = %q{extension for formtastic, adding tag_list and others}
  s.email = %q{rotuka@tokak.ru}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "formtastic_extensions.gemspec",
     "lib/formtastic_extensions.rb",
     "lib/formtastic_extensions/locales/en.yml",
     "lib/formtastic_extensions/locales/ru.yml",
     "lib/formtastic_extensions/semantic_form_builder.rb",
     "milk.gemspec",
     "rails/init.rb",
     "test/formtastic-extensions_test.rb",
     "test/milk_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/krasivotokak/formtastic_extensions}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{additional flexibility for formtastic}
  s.test_files = [
    "test/formtastic-extensions_test.rb",
     "test/milk_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<justinfrench-formtastic>, ["= 0.2.4"])
      s.add_runtime_dependency(%q<redinger-validation_reflection>, ["= 0.3.3"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<justinfrench-formtastic>, ["= 0.2.4"])
      s.add_dependency(%q<redinger-validation_reflection>, ["= 0.3.3"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<justinfrench-formtastic>, ["= 0.2.4"])
    s.add_dependency(%q<redinger-validation_reflection>, ["= 0.3.3"])
  end
end
